name: Label Issues (Permissions Example)
on:
  issues:
    types:
      - opened
jobs: 
  assign-label:
    permissions: 
      issues: write # This workflow will successfully be able to edit issue (add bug label), 
      # but wont be able to explore repo code, or manipualte the actions added to this repo
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        if: contains(github.event.issue.title, 'bug')
        run: |
          curl -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'content-type: application/json' \
          -d '{
              "labels": ["bug"]
            }' \
          --fail


# you can set permissions on job or workflow level